[package]
name = "en-os-remote-assistant"
version = "0.6.0"
edition = "2024"
build = "build.rs"

[dependencies]
teloxide = { version = "0.17", features = ["macros", "rustls"] }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
ashpd = { version = "0.13", features = ["screenshot", "tokio"] }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.12.28", default-features = false, features = ["rustls-tls", "json", "socks"] }
log = "0.4"
dotenvy = "0.15"
pretty_env_logger = "0.4"
serde_json = "1"
url = "2.5.8"
thiserror = "2.0.18"
zip = "8.1.0"
walkdir = "2.5.0"
chrono = "0.4.44"
enigo = "0.6.1"
anyhow = "1.0.102"
log4rs = "1.4.0"
rust-embed = { version = "8.11.0", features = ["include-exclude"] }
openssl = { version = "0.10", features = ["vendored"] }
notify-rust = "4.12.0"
serde_yaml = "0.9.34"
sysinfo = "0.38.4"
shadow-rs = "1.7.1"

[build-dependencies]
shadow-rs = "1.7.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
